# Generated by Django 2.2.6 on 2023-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('mobile_num', models.CharField(max_length=15, verbose_name='Mobile numnber')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('pin_code', models.IntegerField(blank=True, verbose_name='Area pin code')),
            ],
        ),
    ]
