# Generated by Django 6.0 on 2025-12-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pin_code',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80, verbose_name='Address')),
                ('district', models.CharField(max_length=80, verbose_name='District')),
                ('state', models.CharField(max_length=80, verbose_name='State')),
                ('country', models.CharField(max_length=80, verbose_name='Country')),
                ('pin_code', models.IntegerField(blank=True, verbose_name='Pin code')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spw_test.employee')),
            ],
        ),
    ]
