# Generated by Django 6.0 on 2025-12-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0004_address_is_deleted_employee_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=50, verbose_name='Leave name')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('count', models.IntegerField(blank=True, verbose_name='Count')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
