# Generated by Django 6.0 on 2025-12-10 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0005_leavetype_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_leave', models.IntegerField(blank=True, verbose_name='Taken Leave')),
                ('allocated', models.IntegerField(blank=True, verbose_name='Allocated')),
                ('balance', models.IntegerField(blank=True, verbose_name='Balance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spw_test.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spw_test.leavetype')),
            ],
        ),
    ]
