# Generated by Django 6.0 on 2025-12-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0006_employeeleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
