# Generated by Django 6.0 on 2025-12-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0007_employeeleave_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=10, verbose_name='Duration')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_name',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField(verbose_name='Leave Start Date')),
                ('leave_end_date', models.DateField(verbose_name='Leave End Date')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for Leave')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('leave_status', models.CharField(max_length=10, verbose_name='Leave Status')),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spw_test.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spw_test.leavetype')),
            ],
        ),
    ]
