# Generated by Django 6.0 on 2025-12-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0008_leaveduration_alter_leavetype_leave_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavemaster',
            name='leave_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
