# Generated by Django 6.0 on 2025-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0009_alter_employeeleavemaster_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavemaster',
            name='leave_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
