# Generated by Django 6.0 on 2025-12-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0010_alter_employeeleavemaster_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavemaster',
            name='leave_duration',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Leave Duration'),
        ),
    ]
