# Generated by Django 6.0 on 2025-12-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0011_employeeleavemaster_leave_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleavemaster',
            old_name='leave_duration',
            new_name='duration',
        ),
    ]
