# Generated by Django 6.0 on 2025-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0012_rename_leave_duration_employeeleavemaster_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavemaster',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Leave Duration'),
        ),
    ]
