# Generated by Django 6.0 on 2025-12-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0013_alter_employeeleavemaster_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
