# Generated by Django 6.0 on 2025-12-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0014_employeedesignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=15, verbose_name='Basic Salary'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Intern', max_length=255, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Other Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Other Deduction'),
        ),
        migrations.AddField(
            model_name='employee',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Special Allowance'),
        ),
    ]
