# Generated by Django 6.0 on 2025-12-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0015_employee_basic_salary_employee_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
    ]
