# Generated by Django 6.0 on 2025-12-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0016_remove_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Team Lead', max_length=255, verbose_name='Designation'),
        ),
    ]
