# Generated by Django 6.0 on 2025-12-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0017_employee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
    ]
