# Generated by Django 6.0 on 2025-12-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spw_test', '0019_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spw_test.employeedesignation'),
        ),
    ]
